version: '2.1'

services:

  db:
    restart: always
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=password
### Uncomment to enable DB persistance
#    volumes:
#      - ./postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis
### Uncomment to enable REDIS persistance
#    volumes:
#      - ./redis:/data

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
### Uncomment to enable ELASTICSEARCH persistance
#    volumes:
#      - ./elasticsearch:/var/lib/elasticsearch/data

  web:
    restart: always
    build:
      context: .
    command: bash -c "bundle exec rake db:migrate && bundle exec puma -t 5:5 -p 3000 -e ${RACK_ENV:-development}"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
      - redis
    volumes:
      - .:/covoiturage-libre
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - ELASTICSEARCH_URL=http://elastic:changeme@localhost:9200
      - REDIS_URL=redis://redis:6379

  delayedjob:
    build:
      context: .
    command: bash -c "bin/delayed_job run"
    ports:
      - "3001:3000"
    depends_on:
      - db
      - elasticsearch
      - redis
    volumes:
      - .:/covoiturage-libre
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - ELASTICSEARCH_URL=http://elastic:changeme@localhost:9200
      - REDIS_URL=redis://redis:6379
